[build]
  command = "npm run build"
  publish = "dist/"

[build.environment]
NODE_VERSION = "14.19.3"

[dev]
  command = "npm run dev"
  port = 3000
  publish = "dist/"

[[redirects]]
  from = "/timetracker/*"
  to = "https://timetracker.kylecutler.com/:splat"
  status = 301

[[headers]]
  for = "/*"

  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "no-referrer"
    X-Content-Type-Options = "nosniff"